2023-05-15 17:34:13.430 | CRITICAL | __main__:get_city:237 - Критическая ошибка в функции get_city: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6254243703:AAEeo_03r_UI76iSDqsOZPnGweefMmZ1Lq8/sendMessage?chat_id=5618689469&text=%D0%92%D1%8B+%D0%B2%D0%B2%D0%B5%D0%BB%D0%B8+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%3A+%D0%A0%D0%B8%D0%BC (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000214CD9CF010>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
2023-05-15 17:34:58.368 | CRITICAL | __main__:get_result_highprice:620 - Критическая ошибка в функции get_result_highprice: database is locked
2023-05-15 17:35:12.588 | CRITICAL | __main__:highprice:203 - Критическая ошибка в функции highprice: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6254243703:AAEeo_03r_UI76iSDqsOZPnGweefMmZ1Lq8/sendMessage?chat_id=5618689469&text=%D0%92%D0%B2%D0%B5%D0%B4%D0%B8%D1%82%D0%B5+%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000214CDA53990>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
